version: '3.8'

services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    environment:
      - CONNECTION_STRING=Host=localhost;Database=UnsecuredAPIKeys;Username=postgres;Password=devpassword;Port=5432
      - ASPNETCORE_ENVIRONMENT=Development
      - NEXT_PUBLIC_API_URL=http://localhost:7227

  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=UnsecuredAPIKeys
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=devpassword
    ports:
      - "5432:5432"

volumes:
  postgres-data:
